import React from 'react';
import {
  UserOutlined, SafetyOutlined, BellOutlined, BgColorsOutlined, SettingOutlined,
  BankOutlined, ApartmentOutlined, FieldTimeOutlined, GiftOutlined, TeamOutlined,
  IdcardOutlined, SafetyCertificateOutlined, KeyOutlined, UsergroupAddOutlined,
  GlobalOutlined, DollarOutlined, TranslationOutlined, ClockCircleOutlined,
  CalendarOutlined, FundOutlined, PercentageOutlined, CreditCardOutlined,
  FileTextOutlined, ShoppingCartOutlined, ContactsOutlined, ShopOutlined,
  InboxOutlined, BuildOutlined, DesktopOutlined, RocketOutlined,
  CustomerServiceOutlined, WalletOutlined, ProjectOutlined, SoundOutlined,
  PartitionOutlined, CheckCircleOutlined, ClusterOutlined, BranchesOutlined,
  ApiOutlined, FolderOpenOutlined, NumberOutlined, MailOutlined, MessageOutlined,
  AppstoreOutlined, DatabaseOutlined, HistoryOutlined, AuditOutlined,
  EyeInvisibleOutlined, MobileOutlined, InfoCircleOutlined,
} from '@ant-design/icons';
import type { SectionKey } from '../registry/types';

export function buildSectionIconMap(): Record<SectionKey, React.ReactNode> {
  return {
    profile: <UserOutlined />,
    security: <SafetyOutlined />,
    notifications: <BellOutlined />,
    preferences: <BgColorsOutlined />,
    general: <SettingOutlined />,
    appearance: <BgColorsOutlined />,
    organization: <BankOutlined />,
    branches: <ApartmentOutlined />,
    branding: <BgColorsOutlined />,
    working_hours: <FieldTimeOutlined />,
    holidays: <GiftOutlined />,
    users: <TeamOutlined />,
    roles: <IdcardOutlined />,
    permissions: <SafetyCertificateOutlined />,
    sso: <KeyOutlined />,
    portals: <UsergroupAddOutlined />,
    localization: <GlobalOutlined />,
    currencies: <DollarOutlined />,
    languages: <TranslationOutlined />,
    formats: <ClockCircleOutlined />,
    fiscal: <CalendarOutlined />,
    budgets: <FundOutlined />,
    taxes: <PercentageOutlined />,
    banking: <BankOutlined />,
    payment_methods: <CreditCardOutlined />,
    einvoice: <SettingOutlined />,
    templates: <FileTextOutlined />,
    reminders: <ClockCircleOutlined />,
    sales: <ShoppingCartOutlined />,
    crm: <ContactsOutlined />,
    purchases: <ShopOutlined />,
    inventory: <InboxOutlined />,
    mrp: <BuildOutlined />,
    pos: <DesktopOutlined />,
    ecommerce: <RocketOutlined />,
    helpdesk: <CustomerServiceOutlined />,
    hr: <TeamOutlined />,
    payroll: <WalletOutlined />,
    projects: <ProjectOutlined />,
    marketing: <SoundOutlined />,
    workflows: <PartitionOutlined />,
    approvals: <CheckCircleOutlined />,
    integrations: <ClusterOutlined />,
    integrations_health: <ClusterOutlined />,
    webhooks: <BranchesOutlined />,
    api_tokens: <ApiOutlined />,
    documents: <FolderOpenOutlined />,
    numbering: <NumberOutlined />,
    email: <MailOutlined />,
    sms_whatsapp: <MessageOutlined />,
    modules: <AppstoreOutlined />,
    module_requests: <TeamOutlined />,
    backup: <DatabaseOutlined />,
    activity: <HistoryOutlined />,
    audit: <AuditOutlined />,
    gdpr: <EyeInvisibleOutlined />,
    mobile: <MobileOutlined />,
    system: <InfoCircleOutlined />,
    feature_flags: <SettingOutlined />,
  };
}
