#!/usr/bin/env node
// @ts-check
/**
 * audit-loc.mjs (T-0.5, R8.4)
 *
 * Walks `frontend/src/` and `backend/app/` recursively, counts non-blank
 * lines per file, and reports any file over 400 LOC. Two modes:
 *
 *   node scripts/audit-loc.mjs
 *     - Lists files > 400 LOC.
 *     - Writes docs/audit/monolith-watchlist.json.
 *     - Always exits 0.
 *
 *   node scripts/audit-loc.mjs --check
 *     - Same scan.
 *     - Exits 1 if any file exceeds 600 LOC without a
 *       `// monolith-budget-exempt:` marker on line 1.
 *
 *   node scripts/audit-loc.mjs --markdown
 *     - Prints a markdown table of the top 30 offenders to stdout.
 *
 * File-level extensions scanned:
 *   .ts .tsx .js .jsx .mjs .cjs .py
 *
 * Generated artifacts:
 *   docs/audit/monolith-watchlist.json   (always, in default + --check)
 */

import { readFile, readdir, stat, mkdir, writeFile } from 'node:fs/promises';
import { resolve, relative, join, dirname, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const REPO_ROOT = resolve(dirname(__filename), '..');

const SCAN_DIRS = [
  resolve(REPO_ROOT, 'frontend', 'src'),
  resolve(REPO_ROOT, 'backend', 'app'),
];
const OUT_JSON = resolve(REPO_ROOT, 'docs', 'audit', 'monolith-watchlist.json');

const EXTS = new Set(['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs', '.py']);
const IGNORE_DIRS = new Set([
  'node_modules', 'dist', 'build', '.next', '.git', '__pycache__',
  '.venv', 'venv', 'coverage', '.lighthouseci', '.cache', 'playwright-report',
  'test-results',
]);

const WATCHLIST_THRESHOLD = 400;     // listed if > this
const HARD_LIMIT = 600;              // --check fails if > this without marker
const EXEMPT_MARKER = '// monolith-budget-exempt:';

const OWNERS = {
  // crude routing — first match wins
  '/frontend/src/pos/':              '@pos',
  '/frontend/src/components/pos/':   '@pos',
  '/frontend/src/pages/pos':         '@pos',
  '/backend/app/api/pos':            '@pos',
  '/backend/app/services/pos':       '@pos',
  '/frontend':                       '@frontend',
  '/backend':                        '@backend',
};

/** @typedef {{ path: string, loc: number, exempt: boolean, owner: string }} FileEntry */

/**
 * @param {string} dir
 * @returns {AsyncGenerator<string>}
 */
async function* walk(dir) {
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const ent of entries) {
    if (ent.name.startsWith('.') && ent.name !== '.kiro') continue;
    if (IGNORE_DIRS.has(ent.name)) continue;
    const full = join(dir, ent.name);
    if (ent.isDirectory()) {
      yield* walk(full);
    } else if (ent.isFile()) {
      const dot = ent.name.lastIndexOf('.');
      if (dot < 0) continue;
      const extn = ent.name.slice(dot);
      if (EXTS.has(extn)) yield full;
    }
  }
}

/**
 * Count non-blank, non-comment-only lines. We count any line with content as 1.
 * The intent is human-readable LOC, not SLOC — matches typical PR review.
 *
 * @param {string} path
 * @returns {Promise<{ loc: number, exempt: boolean }>}
 */
async function loc(path) {
  const raw = await readFile(path, 'utf8');
  const lines = raw.split(/\r?\n/);
  let count = 0;
  for (const line of lines) {
    if (line.trim() !== '') count++;
  }
  const exempt = lines.length > 0 && lines[0].trim().startsWith(EXEMPT_MARKER);
  return { loc: count, exempt };
}

/**
 * @param {string} relPath
 * @returns {string}
 */
function ownerFor(relPath) {
  const normalized = '/' + relPath.split(sep).join('/');
  for (const [prefix, owner] of Object.entries(OWNERS)) {
    if (normalized.startsWith(prefix)) return owner;
  }
  return '@frontend';
}

async function scan() {
  /** @type {FileEntry[]} */
  const results = [];
  for (const dir of SCAN_DIRS) {
    for await (const file of walk(dir)) {
      try {
        const { loc: count, exempt } = await loc(file);
        const rel = relative(REPO_ROOT, file);
        results.push({
          path: rel.split(sep).join('/'),
          loc: count,
          exempt,
          owner: ownerFor(rel),
        });
      } catch {
        // unreadable file — skip
      }
    }
  }
  results.sort((a, b) => b.loc - a.loc);
  return results;
}

/** @param {FileEntry[]} all */
function watchlist(all) {
  return all.filter((f) => f.loc > WATCHLIST_THRESHOLD);
}

/** @param {FileEntry[]} all */
function violations(all) {
  return all.filter((f) => f.loc > HARD_LIMIT && !f.exempt);
}

/** @param {FileEntry[]} entries @param {number} top */
function renderMarkdown(entries, top = 30) {
  const slice = entries.slice(0, top);
  const lines = [];
  lines.push('# Monolith Watchlist');
  lines.push('');
  lines.push(`> Generated by \`scripts/audit-loc.mjs --markdown\`. Watchlist threshold: **${WATCHLIST_THRESHOLD} LOC**. Hard ceiling: **${HARD_LIMIT} LOC** (R8.4).`);
  lines.push('');
  lines.push('| # | File | LOC | Owner | Exempt |');
  lines.push('|---:|---|---:|---|---|');
  slice.forEach((f, i) => {
    lines.push(`| ${i + 1} | \`${f.path}\` | ${f.loc} | ${f.owner} | ${f.exempt ? 'yes' : ''} |`);
  });
  return lines.join('\n') + '\n';
}

async function main() {
  const args = new Set(process.argv.slice(2));
  const checkMode = args.has('--check');
  const markdownMode = args.has('--markdown');

  const all = await scan();
  const watch = watchlist(all);

  // Always write JSON sidecar.
  await mkdir(dirname(OUT_JSON), { recursive: true });
  await writeFile(
    OUT_JSON,
    JSON.stringify(
      {
        generatedAt: new Date().toISOString(),
        thresholds: { watchlist: WATCHLIST_THRESHOLD, hardLimit: HARD_LIMIT },
        totalFilesScanned: all.length,
        watchlist: watch,
      },
      null,
      2,
    ) + '\n',
  );

  if (markdownMode) {
    process.stdout.write(renderMarkdown(watch));
    return;
  }

  // Default mode — print table to stdout (markdown), exit 0 unless --check.
  process.stdout.write(renderMarkdown(watch));

  if (checkMode) {
    const bad = violations(all);
    if (bad.length > 0) {
      process.stderr.write('\n[audit-loc] FAIL — files exceed hard limit without exempt marker:\n');
      for (const f of bad) {
        process.stderr.write(`  - ${f.path}: ${f.loc} LOC (> ${HARD_LIMIT})\n`);
      }
      process.stderr.write(
        `\nTo exempt, add this as the FIRST line of the file (with ADR link):\n  ${EXEMPT_MARKER} <reason or ADR id>\n`,
      );
      process.exit(1);
    }
    process.stderr.write('\n[audit-loc] OK — no files exceed the hard limit.\n');
  }
}

main().catch((e) => {
  process.stderr.write(`[audit-loc] fatal: ${e?.stack || e}\n`);
  process.exit(1);
});

export { scan, watchlist, violations, renderMarkdown, WATCHLIST_THRESHOLD, HARD_LIMIT };
