# API endpoints for scheduled reports
from fastapi import APIRouter, Depends, HTTPException, Path
from pydantic import BaseModel, Field
from typing import Optional, Any
from datetime import datetime
from app.firestore.scheduled_reports import ScheduledReportRepository
from app.services.auth import get_current_user
from app.services.permissions import require_perm
import uuid

router = APIRouter(prefix="/api/scheduled-reports", tags=["ScheduledReports"])


class ScheduledReportCreate(BaseModel):
    name: str = Field(..., min_length=1, max_length=100)
    report_type: str = Field(..., description="sales_summary|aging|pl|balance_sheet|inventory_summary|custom")
    report_config: dict[str, Any] = Field(default_factory=dict)
    frequency: str = Field(..., description="daily|weekly|monthly")
    day_of_week: Optional[int] = Field(None, ge=0, le=6, description="0=Monday, 6=Sunday (for weekly)")
    day_of_month: Optional[int] = Field(None, ge=1, le=28, description="1-28 (for monthly)")
    hour: int = Field(9, ge=0, le=23, description="Hour of day to run (0-23)")
    recipients: list[str] = Field(default_factory=list, description="Email addresses")
    format: str = Field("pdf", description="pdf|csv|xlsx")
    active: bool = True


class ScheduledReportUpdate(BaseModel):
    name: Optional[str] = None
    report_type: Optional[str] = None
    report_config: Optional[dict[str, Any]] = None
    frequency: Optional[str] = None
    day_of_week: Optional[int] = None
    day_of_month: Optional[int] = None
    hour: Optional[int] = None
    recipients: Optional[list[str]] = None
    format: Optional[str] = None
    active: Optional[bool] = None


# ═══════════════════════════════════════════════════════════════════════════
# Helper function for scheduler (Wave L)
# ═══════════════════════════════════════════════════════════════════════════

def _generate_report_html(org_id: str, report: dict) -> str:
    """Generate HTML body for a scheduled report. Pulls live aggregate data from repositories."""
    rtype = report.get("report_type", "summary")
    name = report.get("name", "Report")
    cfg = report.get("report_config") or {}
    rows: list[str] = []
    try:
        if rtype in ("sales_summary", "aging"):
            from app.firestore.invoices import InvoiceRepository
            invs, total = InvoiceRepository(org_id).list(limit=1000)
            n = len(invs)
            paid = sum(1 for i in invs if (i.get("status") or "").lower() == "paid")
            outstanding = sum(float(i.get("balance_due") or 0) for i in invs)
            grand = sum(float(i.get("total") or 0) for i in invs)
            rows = [
                f"<tr><td>Invoices</td><td>{n}</td></tr>",
                f"<tr><td>Paid</td><td>{paid}</td></tr>",
                f"<tr><td>Total Billed</td><td>{grand:,.2f}</td></tr>",
                f"<tr><td>Outstanding</td><td>{outstanding:,.2f}</td></tr>",
            ]
        elif rtype in ("pl", "profit_loss", "balance_sheet"):
            from app.firestore.journals import JournalEntryRepository
            jes, total = JournalEntryRepository(org_id).list(limit=1000)
            tot_dr = sum(float(j.get("total_debit") or 0) for j in jes)
            tot_cr = sum(float(j.get("total_credit") or 0) for j in jes)
            rows = [
                f"<tr><td>Journal Entries</td><td>{len(jes)}</td></tr>",
                f"<tr><td>Total Debit</td><td>{tot_dr:,.2f}</td></tr>",
                f"<tr><td>Total Credit</td><td>{tot_cr:,.2f}</td></tr>",
            ]
        elif rtype == "inventory_summary":
            from app.firestore.inventory import ItemRepository
            items, total = ItemRepository(org_id).list(limit=1000)
            rows = [
                f"<tr><td>Items</td><td>{len(items)}</td></tr>",
                f"<tr><td>Active</td><td>{sum(1 for i in items if i.get('is_active', True))}</td></tr>",
            ]
        else:
            rows = [f"<tr><td>Type</td><td>{rtype}</td></tr>"]
    except Exception as ex:
        rows = [f"<tr><td>Error gathering data</td><td>{ex}</td></tr>"]
    body = "".join(rows)
    return (
        f"<html><body style='font-family:Arial,sans-serif'>"
        f"<h2>{name}</h2>"
        f"<p>Report type: <b>{rtype}</b><br/>Generated at: {datetime.utcnow().isoformat()}Z</p>"
        f"<table border='1' cellpadding='6' cellspacing='0'>{body}</table>"
        f"<p style='color:#888;font-size:11px'>Auto-generated by Zoho ERP scheduled reports.</p>"
        f"</body></html>"
    )


def _execute_scheduled_report(org_id: str, report_id: str) -> dict:
    """Execute a scheduled report: generate content + email recipients + update timestamps."""
    repo = ScheduledReportRepository(org_id)
    report = repo.get(report_id)
    
    if not report:
        raise ValueError(f"Report {report_id} not found")
    
    now = datetime.utcnow()
    next_run = repo.calculate_next_run(
        report.get("frequency"),
        report.get("day_of_week"),
        report.get("day_of_month"),
        report.get("hour")
    )
    
    # Generate report HTML (pulls live data)
    html_body = _generate_report_html(org_id, report)
    subject = f"[Scheduled Report] {report.get('name', 'Report')} — {now.strftime('%Y-%m-%d')}"
    
    # Send to all recipients (best-effort; SMTP missing => skip gracefully)
    sent_count = 0
    errors: list[str] = []
    recipients = report.get("recipients") or []
    if recipients:
        try:
            from app.services.email_service import send_email
            for to in recipients:
                try:
                    send_email(
                        org_id=org_id,
                        to_email=to,
                        subject=subject,
                        body_html=html_body,
                        entity_type="scheduled_report",
                        entity_id=report_id,
                    )
                    sent_count += 1
                except Exception as ex:
                    errors.append(f"{to}: {ex}")
        except Exception as ex:
            errors.append(f"email_service unavailable: {ex}")
    
    repo.update(report_id, {
        "last_run_at": now.isoformat(),
        "next_run_at": next_run.isoformat() if next_run else None,
        "last_run_status": "ok" if not errors else ("partial" if sent_count else "failed"),
        "last_run_sent": sent_count,
        "last_run_errors": errors[:10],
    })
    
    return {
        "report_id": report_id,
        "executed_at": now.isoformat(),
        "next_run_at": next_run.isoformat() if next_run else None,
        "recipients_count": len(recipients),
        "sent_count": sent_count,
        "errors": errors,
    }


# ═══════════════════════════════════════════════════════════════════════════
# API endpoints
# ═══════════════════════════════════════════════════════════════════════════


@router.get("", dependencies=[Depends(require_perm("reports.read"))])
def list_scheduled_reports(user: dict = Depends(get_current_user)):
    """List all scheduled reports for the organization"""
    org_id = user.get("org_id")
    repo = ScheduledReportRepository(org_id)
    items, total = repo.list(order_by="created_at", order_dir="DESCENDING", limit=100)
    return {"items": items, "total": total}


@router.post("", dependencies=[Depends(require_perm("reports.write"))])
def create_scheduled_report(
    data: ScheduledReportCreate,
    user: dict = Depends(get_current_user)
):
    """Create a new scheduled report"""
    org_id = user.get("org_id")
    repo = ScheduledReportRepository(org_id)

    # Calculate next run time
    next_run = repo.calculate_next_run(
        data.frequency, 
        data.day_of_week, 
        data.day_of_month, 
        data.hour
    )

    report_doc = {
        "id": str(uuid.uuid4()),
        "org_id": org_id,
        "name": data.name,
        "report_type": data.report_type,
        "report_config": data.report_config,
        "frequency": data.frequency,
        "day_of_week": data.day_of_week,
        "day_of_month": data.day_of_month,
        "hour": data.hour,
        "recipients": data.recipients,
        "format": data.format,
        "active": data.active,
        "last_run_at": None,
        "next_run_at": next_run.isoformat() if next_run else None,
        "created_at": datetime.utcnow().isoformat(),
        "created_by": user.get("uid"),
    }
    repo.create(report_doc["id"], report_doc)
    return report_doc


@router.get("/{report_id}", dependencies=[Depends(require_perm("reports.read"))])
def get_scheduled_report(
    report_id: str = Path(...),
    user: dict = Depends(get_current_user)
):
    """Get a scheduled report by ID"""
    org_id = user.get("org_id")
    repo = ScheduledReportRepository(org_id)
    report = repo.get(report_id)
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")
    return report


@router.put("/{report_id}", dependencies=[Depends(require_perm("reports.write"))])
def update_scheduled_report(
    data: ScheduledReportUpdate,
    report_id: str = Path(...),
    user: dict = Depends(get_current_user)
):
    """Update a scheduled report"""
    org_id = user.get("org_id")
    repo = ScheduledReportRepository(org_id)

    existing = repo.get(report_id)
    if not existing:
        raise HTTPException(status_code=404, detail="Report not found")

    update_data = {k: v for k, v in data.model_dump(exclude_unset=True).items() if v is not None}

    # Recalculate next_run if frequency/timing changed
    if any(k in update_data for k in ["frequency", "day_of_week", "day_of_month", "hour"]):
        frequency = update_data.get("frequency", existing.get("frequency"))
        day_of_week = update_data.get("day_of_week", existing.get("day_of_week"))
        day_of_month = update_data.get("day_of_month", existing.get("day_of_month"))
        hour = update_data.get("hour", existing.get("hour"))
        next_run = repo.calculate_next_run(frequency, day_of_week, day_of_month, hour)
        update_data["next_run_at"] = next_run.isoformat() if next_run else None

    repo.update(report_id, update_data)
    return {**existing, **update_data}


@router.delete("/{report_id}", dependencies=[Depends(require_perm("reports.write"))])
def delete_scheduled_report(
    report_id: str = Path(...),
    user: dict = Depends(get_current_user)
):
    """Delete a scheduled report"""
    org_id = user.get("org_id")
    repo = ScheduledReportRepository(org_id)

    existing = repo.get(report_id)
    if not existing:
        raise HTTPException(status_code=404, detail="Report not found")

    repo.delete(report_id)
    return {"message": "Report deleted"}


@router.post("/{report_id}/run-now", dependencies=[Depends(require_perm("reports.write"))])
def run_report_now(
    report_id: str = Path(...),
    user: dict = Depends(get_current_user)
):
    """Manually trigger a scheduled report"""
    org_id = user.get("org_id")
    result = _execute_scheduled_report(org_id, report_id)
    return {"message": "Report executed", **result}


@router.post("/{report_id}/toggle", dependencies=[Depends(require_perm("reports.write"))])
def toggle_report_active(
    report_id: str = Path(...),
    user: dict = Depends(get_current_user)
):
    """Toggle active status of a scheduled report"""
    org_id = user.get("org_id")
    repo = ScheduledReportRepository(org_id)

    existing = repo.get(report_id)
    if not existing:
        raise HTTPException(status_code=404, detail="Report not found")

    new_active = not existing.get("active", True)
    repo.update(report_id, {"active": new_active})

    return {"active": new_active}
