"""
Firestore collection audit — scans backend/app/firestore/*.py and checks:
1. Each repository uses BaseRepository pattern
2. All queries are org_id-scoped
3. No composite indexes relied upon (filtering in Python)

Output: audit/FIRESTORE_AUDIT.md
"""
from __future__ import annotations

import ast
import os
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).parent.parent
REPO_DIR = ROOT / "backend" / "app" / "firestore"
OUT_DIR = ROOT / "audit"
OUT_FILE = OUT_DIR / "FIRESTORE_AUDIT.md"


# ── helpers ───────────────────────────────────────────────────────────────────

def _lines_with(path: Path, pattern: str) -> list[int]:
    results = []
    for i, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if pattern in line:
            results.append(i)
    return results


def _has_base_import(src: str) -> bool:
    return "BaseRepository" in src or "from app.firestore.base" in src or "from .base" in src


def _find_where_calls(path: Path) -> list[tuple[int, str]]:
    """Return (line, snippet) for every .where() call — composite risk."""
    results = []
    for i, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        stripped = line.strip()
        if ".where(" in stripped:
            results.append((i, stripped[:120]))
    return results


def _has_org_id_filter(src: str) -> bool:
    """
    A repo is org_id-scoped if it either:
    - explicitly references org_id in filters, OR
    - extends BaseRepository (which enforces org_id in __init__)
    """
    inherits_base = "BaseRepository" in src
    explicit_filter = "org_id" in src
    return inherits_base or explicit_filter


# ── audit ─────────────────────────────────────────────────────────────────────

def audit_repos() -> list[dict]:
    rows = []
    for py in sorted(REPO_DIR.glob("*.py")):
        if py.name in (
            "__init__.py",
            "base.py",
            "encrypted_mixin.py",
            "references.py",
            "pii_registry.py",
        ):
            continue
        src = py.read_text(encoding="utf-8")
        uses_base = _has_base_import(src)
        org_scoped = _has_org_id_filter(src)
        where_calls = _find_where_calls(py)
        # composite risk: >1 .where() chains on different fields without python-side filtering
        composite_risk = len(where_calls) > 1
        rows.append({
            "file": py.name,
            "uses_base": uses_base,
            "org_scoped": org_scoped,
            "where_calls": where_calls,
            "composite_risk": composite_risk,
        })
    return rows


# ── report ────────────────────────────────────────────────────────────────────

def _infra_notes() -> list[str]:
    base_py = REPO_DIR / "base.py"
    src = base_py.read_text(encoding="utf-8") if base_py.exists() else ""
    notes = [
        "",
        "## Infrastructure helpers",
        "",
        f"- `base.py` `stream_org_docs`: {'yes' if 'stream_org_docs' in src else 'missing'}",
        f"- `base.py` `list_page` / USE_FIRESTORE_QUERY: {'yes' if 'list_page' in src else 'missing'}",
        f"- `query.py` server-side pagination: {'yes' if (ROOT / 'backend/app/firestore/query.py').exists() else 'missing'}",
        "",
    ]
    return notes


def render_md(rows: list[dict]) -> str:
    lines: list[str] = [
        "# Firestore Collection Audit",
        "",
        "Generated by `tools/firestore_audit.py`.",
        "",
        "| File | BaseRepository | org_id scoped | .where() calls | Composite risk |",
        "|------|:-:|:-:|:-:|:-:|",
    ]
    for r in rows:
        base = "OK" if r["uses_base"] else "MISSING"
        org = "OK" if r["org_scoped"] else "WARN"
        count = len(r["where_calls"])
        risk = "WARN" if r["composite_risk"] else "OK"
        lines.append(f"| {r['file']} | {base} | {org} | {count} | {risk} |")

    lines += ["", "## Details", ""]
    for r in rows:
        if not r["where_calls"]:
            continue
        lines.append(f"### {r['file']}")
        for lineno, snippet in r["where_calls"]:
            lines.append(f"- Line {lineno}: `{snippet}`")
        lines.append("")

    lines.extend(_infra_notes())
    lines.extend(_schema_version_notes())
    return "\n".join(lines)


def _schema_version_notes() -> list[str]:
    """Wave S8 — document migration registry coverage."""
    try:
        backend = str(ROOT / "backend")
        if backend not in sys.path:
            sys.path.insert(0, backend)
        from app.firestore.migrations import registered_collections, list_migrations

        lines = ["", "## Schema version registry (S8)", ""]
        for coll in registered_collections():
            versions = list_migrations(coll)
            lines.append(f"- `{coll}`: migrations -> v{max(versions) if versions else 1}")
        lines.append("")
        return lines
    except Exception as exc:
        return ["", f"## Schema version registry: unavailable ({exc})", ""]


def main() -> None:
    OUT_DIR.mkdir(exist_ok=True)
    rows = audit_repos()
    md = render_md(rows)
    OUT_FILE.write_text(md, encoding="utf-8")
    print(md)
    print(f"\nSaved to {OUT_FILE}")

    issues = [r for r in rows if not r["uses_base"] or not r["org_scoped"]]
    if issues:
        print(f"\nWARN: {len(issues)} repositories need attention:")
        for r in issues:
            flags = []
            if not r["uses_base"]:
                flags.append("no BaseRepository")
            if not r["org_scoped"]:
                flags.append("no org_id filter")
            print(f"  - {r['file']}: {', '.join(flags)}")
        sys.exit(1)
    else:
        print("\nOK: All repositories pass audit.")


if __name__ == "__main__":
    main()
