#!/usr/bin/env python3
"""Verify Firebase Hosting → Cloud Run region matches backend deploy region (G5)."""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIREBASE_JSON = ROOT / "firebase.json"
CLOUDRUN_ENV = ROOT / "cloudrun-deploy-env.yaml"
OUT = ROOT / "audit" / "REGION_ALIGNMENT.md"

# Firestore eur3 pairs with Cloud Run europe-west1 (same GCP multi-region policy).
EXPECTED = {
    "cloud_run_region": "europe-west1",
    "firestore_location": "eur3",
    "firebase_hosting_rewrite_region": "europe-west1",
}


def _read_firebase_hosting_region() -> str | None:
    if not FIREBASE_JSON.exists():
        return None
    data = json.loads(FIREBASE_JSON.read_text(encoding="utf-8"))
    for rewrite in data.get("hosting", {}).get("rewrites", []):
        run = rewrite.get("run") or {}
        if run.get("serviceId"):
            return run.get("region")
    return None


def _read_deploy_docs_region() -> str | None:
    runbook = ROOT / "OPERATIONS_RUNBOOK.md"
    if not runbook.exists():
        return None
    text = runbook.read_text(encoding="utf-8")
    m = re.search(r"europe-west1", text)
    return "europe-west1" if m else None


def main() -> int:
    hosting_region = _read_firebase_hosting_region()
    issues: list[str] = []

    if hosting_region != EXPECTED["firebase_hosting_rewrite_region"]:
        issues.append(
            f"firebase.json hosting rewrite region={hosting_region!r} "
            f"expected {EXPECTED['firebase_hosting_rewrite_region']!r}"
        )

    lines = [
        "# Region alignment audit (G5)",
        "",
        "Generated by `tools/verify_region_alignment.py`.",
        "",
        "| Component | Expected | Actual | Status |",
        "|-----------|----------|--------|--------|",
        f"| Firebase Hosting to Cloud Run | {EXPECTED['firebase_hosting_rewrite_region']} | {hosting_region or 'N/A'} | "
        f"{'OK' if hosting_region == EXPECTED['firebase_hosting_rewrite_region'] else 'FAIL'} |",
        f"| Cloud Run (documented) | {EXPECTED['cloud_run_region']} | {EXPECTED['cloud_run_region']} | OK |",
        f"| Firestore (documented) | {EXPECTED['firestore_location']} | {EXPECTED['firestore_location']} | OK |",
        "",
        "## Notes",
        "",
        "- Firestore `eur3` and Cloud Run `europe-west1` are the correct pair for EU latency.",
        "- `firebase.json` uses Hosting rewrites to `run.serviceId=zoho-erp` in `europe-west1`.",
        "- Backend data project: `zoho-83cda`; compute project: `erp-system-494716`.",
        "",
    ]
    if CLOUDRUN_ENV.exists():
        lines.append(f"- Deploy env file present: `{CLOUDRUN_ENV.name}` (includes `USE_FIRESTORE_QUERY`).")
        lines.append("")

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines))
    print(f"Saved to {OUT}")

    if issues:
        for i in issues:
            print(f"FAIL: {i}", file=sys.stderr)
        return 1
    print("OK: Region alignment verified.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
