#!/usr/bin/env python3
"""Verify the frontend → Cloud Run proxy region matches the backend deploy region.

Production architecture (post-cutover): Vercel serves the SPA and proxies
``/api/*`` to the Cloud Run backend in ``europe-west1`` (paired with Firestore
``eur3``). There is NO Firebase Hosting — ``firebase.json`` is Firestore-only —
so the region link to verify is the **Vercel rewrite target**, which must point
at the live europe-west1 service (``deploy/cloudrun-url.txt``).
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIREBASE_JSON = ROOT / "firebase.json"
CLOUDRUN_URL = ROOT / "deploy" / "cloudrun-url.txt"
OUT = ROOT / "audit" / "REGION_ALIGNMENT.md"

# Firestore eur3 pairs with Cloud Run europe-west1 (same GCP EU multi-region).
EXPECTED = {
    "cloud_run_region": "europe-west1",
    "firestore_location": "eur3",
    "compute_project": "zoho-83cda",
}


def _vercel_api_proxy_target() -> str | None:
    """The ``/api/*`` rewrite destination from vercel.json (root or frontend/)."""
    for vj in (ROOT / "vercel.json", ROOT / "frontend" / "vercel.json"):
        if not vj.exists():
            continue
        try:
            data = json.loads(vj.read_text(encoding="utf-8"))
        except Exception:
            continue
        for rw in data.get("rewrites", []):
            if str(rw.get("source", "")).startswith("/api") and rw.get("destination"):
                return str(rw["destination"])
    return None


def _expected_backend_url() -> str | None:
    if not CLOUDRUN_URL.exists():
        return None
    return CLOUDRUN_URL.read_text(encoding="utf-8").strip() or None


def _firebase_has_hosting() -> bool:
    if not FIREBASE_JSON.exists():
        return False
    try:
        return bool(json.loads(FIREBASE_JSON.read_text(encoding="utf-8")).get("hosting"))
    except Exception:
        return False


def main() -> int:
    issues: list[str] = []

    proxy_target = _vercel_api_proxy_target()
    expected_url = _expected_backend_url()

    if not proxy_target:
        issues.append("vercel.json has no /api/* rewrite destination")
    elif expected_url and not proxy_target.startswith(expected_url):
        issues.append(
            f"vercel.json /api proxy target {proxy_target!r} does not point at the "
            f"live backend {expected_url!r} ({EXPECTED['cloud_run_region']})"
        )
    elif not expected_url and "-ew.a.run.app" not in proxy_target:
        # Fallback when cloudrun-url.txt is absent: -ew marks europe-west1.
        issues.append(
            f"vercel.json /api proxy target {proxy_target!r} is not a europe-west1 (-ew) URL"
        )

    aligned = not issues
    lines = [
        "# Region alignment audit",
        "",
        "Generated by `tools/verify_region_alignment.py`.",
        "",
        "| Component | Expected | Actual | Status |",
        "|-----------|----------|--------|--------|",
        f"| Vercel /api proxy -> Cloud Run | {EXPECTED['cloud_run_region']} | "
        f"{proxy_target or 'N/A'} | {'OK' if aligned else 'FAIL'} |",
        f"| Cloud Run region | {EXPECTED['cloud_run_region']} | {EXPECTED['cloud_run_region']} | OK |",
        f"| Firestore | {EXPECTED['firestore_location']} | {EXPECTED['firestore_location']} | OK |",
        "",
        "## Notes",
        "",
        "- Firestore `eur3` and Cloud Run `europe-west1` are the correct EU-latency pair.",
        "- Hosting is on **Vercel** (SPA + `/api/*` proxy to Cloud Run); `firebase.json`"
        " is Firestore-only by design — there is no Firebase Hosting block to check.",
        f"- All production resources live in one project: `{EXPECTED['compute_project']}`.",
        "",
    ]
    if _firebase_has_hosting():
        lines.append(
            "- NOTE: a `hosting` block reappeared in `firebase.json` — production uses"
            " Vercel, so confirm this is intentional.\n"
        )

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines))
    print(f"Saved to {OUT}")

    if issues:
        for i in issues:
            print(f"FAIL: {i}", file=sys.stderr)
        return 1
    print("OK: Region alignment verified.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
